### ISSUE TITLE
Webcam bug

### ISSUE THREAD

**Issue by AliDschie** [cindyloo/rockstar-ai#1]
Hi,

I just tested the application and instead of showing und using the webcam picture I just took it displayed the picture of my friend who was using the application at the same time at another location. 

Cheers

**Comment by cindyloo** [comment]
hi Ali! thank you for this reminder. At the beginning, I chose not to keep the individual pictures and decided to just overwrite the file. That of course doesn't work so well with multiple people taking simultaneous pictures, - I'll scale it up this evening and will later write a process to clean out the temporary images at some point - or perhaps ask each user whether I might incorporate them into the project.

**Comment by cindyloo** [comment]
@AliDschie fixed. let me know any other suggestions!
